# Generated by Django 2.2.1 on 2019-06-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190605_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('pk',)},
        ),
    ]
